### ISSUE TITLE
reversing warmup1

### ISSUE THREAD

**Issue by madneal** [mzfr/ctf-writeups#1]
Hi, I have a question. When I downloaded the `run` file in kali linux (64bit version). Firstly, I tried to run by `./run`, it indicates:"bash: ./run: Permission denied". Then, I tried to modify the permission of the file by ` chmod +x run` and then continue to run the file by `./run`. It indicates that `bash: ./run: No such file or directory`.

I am really confused that how to run the file. Thanks in advance.

**Comment by mzfr** [comment]
@neal1991 you closed the issue does that mean the problem is fixed now?

**Comment by madneal** [comment]
@mzfr yep, 32-bit ELF can be run in kali linux (64-bit) by `apt-get install libselinux1:i386`
