### ISSUE TITLE
Show full zsteg command

### ISSUE THREAD

**Issue by coopermor** [mzfr/ctf-writeups#3]
Can you include how you extract the full data? This is where I got stuck in the CTF.

https://github.com/mzfr/ctf-writeups/blame/57b4d4d9ae3f9c8995943cfaea27d25d7f3a4a66/Securinets_Prequals_2K19/misc/EZ/README.md#L33

**Comment by mzfr** [comment]
@coopermor Thanks for pointing that out. I have fixed it
